#############################################################################
# Make it under Ubuntu, so don't know if it works for others !!!
# Makefile for building: cmda
#	make 		------ To build
#	make install	------ Install at /opt/cmda/
#			------ make a link of [/opt/cmda/cmda] to [/usr/local/bin/]
#	make clean	------ Clean all building output
#	make uninstall  ------ Uninstall it, delete all data related to it!

# If you use Qt, you can open this project with it.
# I used Qt Creator 3.0.1 Based on Qt 5.2.1 (GCC 4.8.2, 64 bit)

# By the way, this file is a copy of the Makefile generated by Qt Creator, and I delete
# much more thing which is not necessary, it works for me.

# Have fun, enjoy it !
#############################################################################

####### Compiler, tools and options
CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=c++0x -Wall -W -fPIE $(DEFINES)
INCPATH       = 
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = 

INSTALLDEST   = /opt/cmda
CMDAUSRDATA   = ~/.cmda/
SHEETSENDATA  = ./sheets/en/*
SHEETSENDEST  = /opt/cmda/sheets/en/
SHEETSZHDATA  = ./sheets/zh/*
SHEETSZHDEST  = /opt/cmda/sheets/zh
SOURCEFILE    = cmda.pro \
		colorize.cpp \
		debug.h \
		main.cpp \
		README.md \
		sheets.cpp \
		colorize.h \
		LICENSE \
		Makefile \
		sheets \
		sheets.h
SOURCEFILEDEST= /opt/cmda/src/

####### Output directory
OBJECTS_DIR   = ./

####### Files
SOURCES       = ./main.cpp \
		./colorize.cpp \
		./sheets.cpp

OBJECTS       = main.o \
		colorize.o \
		sheets.o

TARGET  = cmda

####### Building
$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS)

###### Install and Uninstall
install:
	./cmda
	sudo cp $(SHEETSENDATA) $(SHEETSENDEST)
	sudo cp $(SHEETSZHDATA) $(SHEETSZHDEST)
	sudo mkdir -p $(SOURCEFILEDEST)
	sudo cp $(SOURCEFILE) $(SOURCEFILEDEST)
	@echo "Install Done."
uninstall:
	sudo rm -r $(INSTALLDEST)
	@echo "Do you want to delete all the data in $(CMDAUSRDATA) ?(y/n)"\
	read choice\
	if [ "$x" = "y" ];then;rm -r $(CMDAUSRDATA);fi
	@echo "Uninstall Done."
	
####### Implicit rules
%.o:%.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

clean:
	rm -f *.o cmda
