#############################################################################
# Make it under Ubuntu, so don't know if it works for others !!!
# Makefile for building: ref
#	make 		------ To build
#	make install	------ Install at /opt/ref/
#			------ make a link of [/opt/ref/bin/ref] to [/usr/local/bin/ref]
#	make clean	------ Clean all building output
#	make uninstall  ------ Uninstall it, delete all data related to it!
#
# If you use Qt, you can open this project with it.
# I used Qt Creator 3.0.1 Based on Qt 5.2.1 (GCC 4.8.2, 64 bit)
#
# By the way, this file is a copy of the Makefile generated by Qt Creator, and I delete
# much more thing which is not necessary, it works for me.
#
# Have fun, enjoy it !
#############################################################################
####### Compiler, tools and options
CXX           = g++
CFLAGS        = -m32 -pipe -O2 -Wall -W -fPIE
CXXFLAGS      = -m32 -pipe -O2 -std=c++0x -Wall -W -fPIE
LINK          = g++
LFLAGS        = -m32 -Wl,-O1

PREFIX          = /opt
PREFIX_LINK     = /usr/bin

PROG_NAME       = ref
PROG_ROOT_DIR   = ${PREFIX}/ref
PROG_BIN_DIR    = $(PROG_ROOT_DIR)/bin
PROG_SHEETS_DIR = ${PROG_ROOT_DIR}/sheets

BUILD_DIR     = ./objs
STATIC_DATA_DIR = ./data
PROG_VERSION_FILE = ${STATIC_DATA_DIR}/version

RM            = rm -f
MKDIR         = mkdir -p
LN            = ln -s
INSTALL       = install
CP	      = cp
MV            = mv

####### Files
SOURCES       = ./src/main.cpp \
		./src/upvf.cpp \
		./lib/colorize.cpp \
		./lib/linuxutility.cpp \
		./lib/value.cpp \
		./lib/version.cpp \
		./src/setting.cpp \
		./src/help.cpp \
		./src/core.cpp 
OBJECTS       = ${BUILD_DIR}/colorize.o \
		${BUILD_DIR}/linuxutility.o \
		${BUILD_DIR}/value.o \
		${BUILD_DIR}/version.o \
		${BUILD_DIR}/setting.o \
		${BUILD_DIR}/help.o \
		${BUILD_DIR}/core.o

#######
.PHONY:all install uninstall clean
####### Building
all:$(OBJECTS) ${BUILD_DIR}/main.o ${BUILD_DIR}/upvf.o first
	$(LINK) $(LFLAGS) -o ${BUILD_DIR}/$(PROG_NAME) $(OBJECTS) ${BUILD_DIR}/main.o

first:
	$(LINK) $(LFLAGS) -o ${BUILD_DIR}/upvf $(OBJECTS) ${BUILD_DIR}/upvf.o
	${BUILD_DIR}/upvf
	${MV} ./version ${BUILD_DIR}/

install:all
	$(INSTALL) -d ${DESTDIR}$(PROG_BIN_DIR) ${DESTDIR}${PROG_SHEETS_DIR}
	$(INSTALL) ${BUILD_DIR}/$(PROG_NAME) ${DESTDIR}$(PROG_BIN_DIR)
	#$(LN) ${DESTDIR}$(PROG_BIN_DIR)/$(PROG_NAME) ${DESTDIR}$(PREFIX_LINK)/$(PROG_NAME)
	$(CP) -r ${STATIC_DATA_DIR}/sheets/* ${DESTDIR}$(PROG_SHEETS_DIR)/
	$(CP) -r ${PROG_VERSION_FILE} ${DESTDIR}$(PROG_BIN_DIR)/
	$(CP) -r ${STATIC_DATA_DIR}/config ${DESTDIR}$(PROG_ROOT_DIR)/config.template
	@echo "Install Done."

uninstall:
	$(RM) -r ${DESTDIR}$(PROG_BIN_DIR)
	$(RM) ${DESTDIR}$(PREFIX_LINK)/$(PROG_NAME)
	@echo "Uninstall Done."

####### Implicit rules
.SUFFIXES: .o .c .cpp .cc .cxx .C
.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"
.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"
.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"
.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"
####### Compile
${BUILD_DIR}/upvf.o: ./src/upvf.cpp \
	./src/help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ${BUILD_DIR}/upvf.o ./src/upvf.cpp

${BUILD_DIR}/main.o: ./src/main.cpp \
	./src/help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ${BUILD_DIR}/main.o ./src/main.cpp

${BUILD_DIR}/colorize.o:./lib/colorize.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ${BUILD_DIR}/colorize.o ./lib/colorize.cpp

${BUILD_DIR}/linuxutility.o: ./lib/linuxutility.cpp \
		./lib/linuxutility.h \
		./lib/colorize.h \
		./lib/debug.h
		$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ${BUILD_DIR}/linuxutility.o ./lib/linuxutility.cpp

${BUILD_DIR}/value.o:./lib/value.cpp \
	./lib/value.h \
	./lib/colorize.h \
	./lib/debug.h \
	./lib/linuxutility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ${BUILD_DIR}/value.o ./lib/value.cpp

${BUILD_DIR}/version.o: ./lib/version.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ${BUILD_DIR}/version.o ./lib/version.cpp

${BUILD_DIR}/setting.o:      ./src/setting.cpp \
		./src/setting.h \
		./lib/libwlc.h \
		./lib/debug.h \
		./lib/colorize.h \
		./lib/value.h \
		./lib/linuxutility.h \
		./lib/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ${BUILD_DIR}/setting.o ./src/setting.cpp

${BUILD_DIR}/help.o: ./src/help.cpp \
	./src/help.h \
	./src/core.h \
	./src/setting.h \
	./lib/libwlc.h \
	./lib/debug.h \
	./lib/colorize.h \
	./lib/value.h \
	./lib/linuxutility.h \
	./lib/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ${BUILD_DIR}/help.o ./src/help.cpp

${BUILD_DIR}/core.o: ./src/core.cpp \
	./src/core.h \
	./src/setting.h \
	./lib/libwlc.h \
	./lib/debug.h \
	./lib/colorize.h \
	./lib/value.h \
	./lib/linuxutility.h \
	./lib/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ${BUILD_DIR}/core.o ./src/core.cpp

######  Cleanup
clean:
	rm -f ${BUILD_DIR}/*.o ${BUILD_DIR}/ref ${BUILD_DIR}/version ${BUILD_DIR}/upvf
