#############################################################################
# Make it under Ubuntu, so don't know if it works for others !!!
# Makefile for building: cmda
#	make 		------ To build
#	make install	------ Install at /opt/cmda/
#			------ make a link of [/opt/cmda/cmda] to [/usr/local/bin/]
#	make clean	------ Clean all building output
#	make uninstall  ------ Uninstall it, delete all data related to it!

# If you use Qt, you can open this project with it.
# I used Qt Creator 3.0.1 Based on Qt 5.2.1 (GCC 4.8.2, 64 bit)

# By the way, this file is a copy of the Makefile generated by Qt Creator, and I delete
# much more thing which is not necessary, it works for me.

# Have fun, enjoy it !
#############################################################################

####### Compiler, tools and options
CXX           = g++
CFLAGS        = -m64 -pipe -O2 -Wall -W -fPIE
CXXFLAGS      = -m64 -pipe -O2 -std=c++0x -Wall -W -fPIE
LINK          = g++
LFLAGS        = -m64 -Wl,-O1

PREFIX_LINK   = /usr/local
BIN_LINK_DIR  = $(PREFIX_LINK)/bin

PROG_HOME     = /opt/cmda
PROG_BIN_DIR  = $(PROG_HOME)/bin
PROG_SHEET_EN = $(PROG_HOME)/sheets/en
PROG_SHEET_ZH = $(PROG_HOME)/sheets/zh
PROG_USR_DIR  = ~/.cmda

TARGET_NAME   = cmda

RM            = rm -f
MKDIR         = mkdir -p
LN            = ln -s
INSTALL       = install

####### Files
SOURCES       = ./main.cpp \
		./colorize.cpp \
		./sheets.cpp

OBJECTS       = main.o \
		colorize.o \
		sheets.o
#######
.PHONY:all install uninstall reinstall clean

####### Building
all:$(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET_NAME) $(OBJECTS)

###### Install Uninstall Reinstall
install:all
	sudo $(INSTALL) -d $(PROG_BIN_DIR) $(PROG_SHEET_EN) $(PROG_SHEET_ZH)
	sudo $(INSTALL) $(TARGET_NAME) $(PROG_BIN_DIR)
	sudo $(LN) $(PROG_BIN_DIR)/$(TARGET_NAME) $(BIN_LINK_DIR)/$(TARGET_NAME)
	sudo $(INSTALL) -t $(PROG_SHEET_EN) ./sheets/en/*
	sudo $(INSTALL) -t $(PROG_SHEET_ZH) ./sheets/zh/*
	@echo "Install Done."

uninstall:
	sudo $(RM) -r $(PROG_HOME)
	sudo $(RM) $(BIN_LINK_DIR)/cmda
	@echo "Do you want to delete all the data in $(PROG_USR_DIR) ?(y/n)"
	@read choice; if [ "$$choice" = "y" ];then $(RM) -r $(PROG_USR_DIR);fi
	@echo "Uninstall Done."
	
reinstall:all
	sudo $(RM) $(PROG_BIN_DIR)/cmda
	sudo $(INSTALL) $(TARGET_NAME) $(PROG_BIN_DIR)
	@echo "Reinstall Done."
####### Implicit rules
%.o:%.cpp
	$(CXX) -c $(CXXFLAGS) -o "$@" "$<"
######  Cleanup
clean:
	rm -f *.o cmda
